---
title: "mass_figures"
author: "Elena; revised by Konrad"
date: "3/1/2021; revised 3/2023"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
```

```{r}
# read data-- mean f1 for 5-fold CV all RF models using MASS labels
aggf1RF <- read.csv('MIP_classify_RF_f1_score_agg.csv') %>%
  mutate(response = factor(response, levels = c("difcoMB", "HMBcmpt", "HMBpep", "HMBaa", 
                                                "HMBlips", "HMBoligo", "HMBorg", "HMBntrl", 
                                                "HMBamisug", "HMBacdsug", "HMB--"))) %>%
  arrange(response)
colnames(aggf1RF) <- c("num_pred", "response", "f1_mean", "f1_std")

# read data-- RF control without MASS
rfCntrl <- read.csv('compare_classify_RF_f1_score_agg.csv') %>%
  mutate(response = factor(response, levels = c("difcoMB", "HMBcmpt", "HMBpep", "HMBaa", 
                                                "HMBlips", "HMBoligo", "HMBorg", "HMBntrl", 
                                                "HMBamisug", "HMBacdsug", "HMB--"))) %>%
  arrange(response) %>%
  mutate(num_pred = 'RFcntrl') %>%
  select(num_pred, response, mean, std)
colnames(rfCntrl) <- c("num_pred", "response", "f1_mean", "f1_std")

# combine mean f1 and control
comboF1 <- aggf1RF %>%
  mutate(num_pred = as.character(num_pred)) %>%
  bind_rows(rfCntrl)

# binary growth profiles
gp <- readxl::read_xlsx('growth_profiles_binary.xlsx')
### from github (Forchielli'2023): https://github.com/segrelab/marine_heterotrophs/blob/main/data/growth_profiles.xlsx
### gp <- readxl::read_xlsx("growth_profiles.xlsx") %>% mutate(across(-strain, ~if_else(.x>0, 1, 0)))
```

```{r}
# compute Shannon entropy
entropy <- function(target) {
  freq <- table(target)/length(target)
  # vectorize
  vec <- as.data.frame(freq)[,2]
  #drop 0 to avoid NaN resulting from log2
  vec<-vec[vec>0]
  #compute entropy
  -sum(vec * log2(vec))
}

gp_ent <- lapply(gp[,-1], entropy) 
ent <- data.frame(medium = names(gp_ent),
                  entropy = unlist(gp_ent))
```

```{r}
### Figure raw phenotype matrix as heatmap ###

# order rows and columns with hclust
marine_hm_clust_org <- hclust(dist(column_to_rownames(gp, "strain"), method = "euclidian"), method = "complete")
marine_hm_clust_cond <- hclust(dist(t(select(gp, -strain)), method = "euclidian"), method = "complete")

marine_hm <- gp %>%
  pivot_longer(-strain, names_to = "condition", values_to = "phenotype")

fig_marine_hm <- marine_hm %>%
  mutate(strain = fct_relevel(strain, marine_hm_clust_org$labels[marine_hm_clust_org$order]),
    condition = fct_relevel(condition, marine_hm_clust_cond$labels[marine_hm_clust_cond$order])) %>%
  # complete(num_pred, response) %>%
  # mutate(pred = if_else(is.na(f1_mean), 1, 0)) %>%
  # group_by(response) %>% mutate(x = sum(pred)) %>% ungroup() %>%
  # arrange(desc(x)) %>% mutate(response = fct_inorder(response)) %>%
  # mutate(num_pred = as.factor(num_pred)) %>%
  ggplot(., aes(x = condition, y = strain)) +
  geom_tile(aes(fill = as.factor(phenotype)), colour = "gray") +
  scale_fill_viridis(discrete = TRUE, labels = c("0" = "Negative", "1" = "Positive"), name = "Growth") +
  theme_minimal() +
  theme(text = element_text(size = 14, color = "black"),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "bottom",
        axis.title.x = element_blank(), axis.title.y = element_blank())
fig_marine_hm
```

```{r}
marine_hm_cond_var <- marine_hm %>%
  group_by(condition) %>%
  summarise(var = var(phenotype)) %>%
  ungroup() %>%
  arrange(desc(var)) %>%
  mutate(rank = fct_reorder(condition, var))
```


```{r warning=FALSE}
### Figure heatmap selected predictors
marine_mass_p <- aggf1RF %>%
  complete(num_pred, response) %>%
  mutate(pred = if_else(is.na(f1_mean), 1, 0)) %>%
  group_by(response) %>% mutate(x = sum(pred)) %>% ungroup() %>%
  arrange(desc(x)) %>% mutate(response = fct_inorder(response))

fig_marine_mass_p <- marine_mass_p %>%
  mutate(num_pred = as.factor(num_pred)) %>%
  ggplot(., aes(x = num_pred, y = response)) +
  geom_tile(aes(fill = as.factor(pred)), colour = "gray") +
  labs(x = "Number of Predictors") +
  scale_fill_manual(values = c("0" = "black", "1" = "gray"), guide = NULL) +
  theme_minimal() +
  theme(text = element_text(size = 14, color = "black"),
        axis.title.y = element_blank(), axis.text.y = element_blank())
fig_marine_mass_p

### Figure dot plots: Accuracy
fig_marine_mass_acc <- comboF1 %>%
  mutate(response = factor(response, levels = names(ord))) %>%
  mutate(num_pred = ifelse(num_pred == "RFcntrl", "C", num_pred)) %>%
  mutate(num_pred = factor(num_pred, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, "C"))) %>%
  ggplot(aes(x = as.factor(num_pred), y = f1_mean, color = response)) +
  geom_point(aes(size = f1_std), alpha = .75) +
  theme_classic() +
  theme(text = element_text(size = 14),
        legend.justification=c(1,0), 
        legend.position=c(1,0)) +
  scale_color_viridis(discrete = TRUE) +
  facet_wrap(~response) +
  guides(color = "none") +
  labs(y = "Mean Accuracy Score",
       x = "Number of Predictors",
       color = "Medium",
       size = "Standard Deviation")
fig_marine_mass_acc

### Figure bar graphs: Entropy
fig_marine_mass_ent <- ent %>%
  mutate(medium = factor(medium, levels = levels(marine_mass_p$response))) %>%
  ggplot(aes(x = medium, y = entropy, fill = medium)) +
  geom_col(width = 1) +
  theme_classic() +
  theme(text = element_text(size = 14, color = "black"),
        axis.text.y = element_text(hjust = 0.5, colour = "black")) +
  scale_fill_viridis(discrete = TRUE, direction = -1) +
  scale_y_continuous(breaks = c(0,.5,1)) +
  # scale_y_continuous(breaks = seq(0,1,.2)) +
  guides(fill = "none") +
  labs(x = "",
       y = "Shannon Entropy") +
  coord_flip()
fig_marine_mass_ent
```

Assemble plot
```{r}
png(filename = "fig-marine-mass.png", width = 4000, height = 3500, res = 300)
wrap_plots(A = fig_marine_hm,
           B = fig_marine_mass_p,
           C = fig_marine_mass_ent, 
           D = fig_marine_mass_acc,
           design = layout <- '
ABC
ADD
', heights = c(1,1), widths = c(3,3,1)) +
  plot_annotation(tag_levels = "A") & 
  theme(plot.tag = element_text(size = 18))
dev.off()
```

```{r}
### Figure S2A ###
x <- gp %>%
  select(-strain) %>%
  colSums()

# times selected vs entropy w/ and w/o difco
p1 <- data.frame(medium = names(x), 
           ngrow = x,
           nsel = c(0, 5, 6, 8, 7, 5, 6, 9, 1, 4, 4)) %>%
  inner_join(ent, by = 'medium') %>%
  ggplot(aes(x = entropy, y = nsel, label = medium)) +
  geom_point() +
  scale_y_continuous(breaks = scales::pretty_breaks(10)) +
  theme_classic() +
  theme(text = element_text(size = 14)) +
  labs(y = "Times Selected as Predictor",
       x = "Shannon Entropy")
p1
```
