---
title: "yeast data figures"
author: "Elena & Konrad"
date: "08/09/2023"
output: html_document
---

# Set-Up and Data Loading
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
library(patchwork)
```

Helper function
```{r}
my_breaks <- function(x, b = 5){
  x <- as.numeric(x)
  ret <- sapply(x, function(xx){
    ifelse(xx %% b == 0 | xx == x[[1]] | xx == x[[length(x)]], as.character(xx), '')
  })
  return(ret)
}
```

```{r}
### import and format yeast data ###
rawDat <- readxl::read_xlsx("summary_2ndEdition.xlsx", sheet = "Sheet1", trim_ws = TRUE) %>% 
  filter(!strain == "dummyVars") %>% # second row has the dummy vars, remove
  rename(species = strain)

# get list of carbon sources included in analysis
cSources <- readxl::read_xlsx("summary_2ndEdition.xlsx", sheet = "Sheet2", trim_ws = TRUE) 
# subset features
rawDat <- rawDat %>% select(c(cSources$carbon_source, "species"))
# remove the word "growth" from column names
rawDat <- rawDat %>%
  setNames(gsub(" growth", "", names(.)))

# replace characters with numbers, see above
yeastdat <- rawDat %>%
  mutate(across(everything(), ~replace(., . %in%  c("D", "V", "W") , 1))) %>%
  mutate(across(everything(), ~replace(., . == "+", 2))) %>%
  mutate(across(everything(), ~replace(., . == "-", 0))) %>%
  mutate(across(everything(), ~replace(., . == "?", NA)))

# remove rows with unknown feature values (NAs)
yeastdat <- yeastdat %>%
  drop_na()

# read in f1 scores
yeastf1 <- read_csv( "MIP_classify_f1_scores_greedy2_20200416.csv") %>%
  dplyr::rename(f1_score = `f1 score`) %>%
  arrange(num_predictors)
### note that D-Glucose is excluded from models because almost all strains exhibited growth on it ###
```

# Figure: Yeast dataset main figure
## Phenotype matrix

```{r}
### Figure raw phenotype matrix as heatmap ###

# order rows and columns with hclust
yeast_hm_clust_org <- hclust(dist(column_to_rownames(yeastdat, "species"), method = "euclidian"), method = "complete")
yeast_hm_clust_cond <- hclust(dist(t(select(yeastdat, -species)), method = "euclidian"), method = "complete")
yeast_hm <- yeastdat %>%
  pivot_longer(-species, names_to = "condition", values_to = "phenotype") %>%
  mutate(species = fct_relevel(as.character(species), yeast_hm_clust_org$labels[yeast_hm_clust_org$order]),
    condition = fct_relevel(condition, yeast_hm_clust_cond$labels[yeast_hm_clust_cond$order])
    )

fig_yeast_hm <- yeast_hm %>%
  ggplot(., aes(x = condition, y = species)) +
  geom_tile(aes(fill = as.factor(phenotype))) +
  scale_fill_viridis_d(labels = c("0" = "Negative", "1" = "Variable, weak,\n delayed", "2" = "Positive"), name = "Growth") +
  labs(y = "Species") +
  theme_minimal() +
  theme(text = element_text(size = 14, color = "black"),
        legend.text = element_text(size = 10, color = "black"),
        legend.title = element_text(size = 10, color = "black"),
        legend.key.size = unit(0.8, "lines"),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.line.y = element_line(colour = "black", linewidth = rel(1)))
fig_yeast_hm
```


```{r}
### Figure heatmap marginal conditions ###
# percentage of bacdive species fermenting on each carbon source
fig_yeast_hm_cond <- yeast_hm %>%
  ggplot(aes(x = condition, fill = as.factor(phenotype))) +
  geom_bar(position = "fill", width = 1) +
  scale_y_continuous(labels = scales::percent, breaks = c(0,.5,1)) +
  theme_classic() +
  theme(text = element_text(size = 14, color = "black"),
        axis.title = element_blank(), 
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        axis.text.y = element_text(hjust = 0.5, color = "black")) +
    #theme(text = element_blank()) +
  scale_fill_viridis_d(guide = NULL) +
  guides(fill = "none") +
  labs(x = "Carbon Source",
       y = "Percentage of Species")
fig_yeast_hm_cond
```

```{r}
### Figure heatmap marginal organisms ###
# the order of the bars (strains) matches the order of the species in the heat map
fig_yeast_hm_org <- yeast_hm %>%
  ggplot(aes(x = species, fill = as.factor(phenotype))) +
  geom_bar(position = "fill", width = 1) +
  scale_y_continuous(labels = scales::percent, breaks = c(0,.5,1)) +
  theme_classic() +
  theme(text = element_text(size = 14, color = "black"),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        axis.ticks.y = element_blank()) +
  scale_fill_viridis_d(guide = NULL) +
  #guides(fill = "none") +
  labs(x = "Species",
       y = "Carbon Sources") +
  coord_flip()
fig_yeast_hm_org
```

```{r}
# png(filename = "fig-bacdive1-heatmap.png", width = 4500, height = 3000, res = 300)
 wrap_plots(A = fig_yeast_hm_cond,
           B = guide_area(), 
           C = fig_yeast_hm,
           D = fig_yeast_hm_org,
           design = layout <- '
AB
CD
', heights = c(1, 9), widths = c(6,1), guides = 'collect') +
  plot_annotation(tag_levels = "A") & 
  theme(plot.tag = element_text(size = 18))
# dev.off()
```

## Phenotype variance explored
```{r}
yeast_hm_cond_var <- yeast_hm %>%
  group_by(condition) %>%
  summarise(var = var(phenotype)) %>%
  ungroup() %>%
  arrange(desc(var)) %>%
  mutate(rank = fct_reorder(condition, var))

# ranked by variance
yeast_hm_cond_var %>%
  ggplot(., aes(rank, var)) +
  geom_point()+
  theme_minimal() +
  theme(text = element_text(size = 14, color = "black"),
        legend.text = element_text(size = 10, color = "black"),
        legend.title = element_text(size = 10, color = "black"),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

# density plot
yeast_hm_cond_var %>%
  ggplot(., aes(var)) +
  geom_histogram(aes(y = after_stat(density)), binwidth = .05) +
  geom_density() +
  theme_minimal()
# both large datasets combined
yeast_hm_cond_var %>% mutate(DATASET = "3") %>%
  bind_rows(., marine_hm_cond_var%>% mutate(DATASET = "1")) %>%
  bind_rows(., bacdive1_hm_cond_var%>% mutate(DATASET = "2")) %>%
  ggplot(., aes(var)) +
  geom_histogram(aes(y = after_stat(density), fill = DATASET), binwidth = .1) +
  geom_density() +
  geom_vline(xintercept = .35) +
  theme_minimal()

(ggraph::ggraph(tidygraph::as_tbl_graph(yeast_hm_clust_cond), layout = 'dendrogram', height = height) + 
  ggraph::geom_edge_elbow()) /
  (yeast_hm %>%
  group_by(condition) %>%
  summarise(var = var(phenotype)) %>%
  ungroup() %>%
  arrange(desc(var)) %>%
  mutate(hclust_order = fct_relevel(condition, yeast_hm_clust_cond$labels[yeast_hm_clust_cond$order])) %>%
  ggplot(., aes(hclust_order, var)) +
  geom_point()+
  theme_minimal() +
  theme(text = element_text(size = 14, color = "black"),
        legend.text = element_text(size = 10, color = "black"),
        legend.title = element_text(size = 10, color = "black"),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
) 
```


```{r}
x <- yeast_hm %>%
  filter(species != "Saccharomycodes sinensis") %>%
  mutate(phenotype = as.numeric(phenotype)) %>%
  pivot_wider(names_from = species, values_from = phenotype) %>%
  column_to_rownames("condition")

pr.out <- prcomp(x, scale = TRUE)
pr.var <- pr.out$sdev^2
pve <- pr.var / sum(pr.var)
round(pve, 2)
plot(pr.out$x[,1], pr.out$x[,2], type = "n")
text(pr.out$x[,1], pr.out$x[,2], labels = rownames(pr.out$x))

set.seed(2)
km.out <- kmeans(x, 2, nstart = 50)
plot(pr.out$x[,1], pr.out$x[,2], type = "n")
text(pr.out$x[,1], pr.out$x[,2], labels = rownames(pr.out$x), col = (km.out$cluster + 1))
```


## MASS applied
```{r}
# format data
# yeastf1_wide <- yeastf1 %>%
#   pivot_wider(names_from = response, values_from = `f1 score`)
# # c sources selected as predictors will have NA, change to 0
# yeastf1_wide[is.na(yeastf1_wide)] <- 1
# # anything w f1 score was a response & all f1 < 1, so convert all < 1 to 0, meaning NOT chosen as predictor
# yeastf1_wide[yeastf1_wide < 1] <- 0
# 
# # create an order for c sources from least to most times selected as predictor
# ord <- yeastf1_wide %>% 
#   select(-num_predictors) %>%
#   colSums() %>% 
#   sort()

yeast_mass_p <- yeastf1 %>%
  complete(num_predictors, response) %>%
  mutate(pred = if_else(is.na(f1_score), 1, 0)) %>%
  group_by(response) %>% mutate(x = sum(pred)) %>% ungroup() %>%
  arrange(desc(x)) %>% mutate(response = fct_inorder(response))
```

```{r}
### Figure fig_yeast_mass ###
# format for heatmap
yeast_mass_p <- yeastf1 %>%
  complete(num_predictors, response) %>%
  mutate(pred = if_else(is.na(f1_score), 1, 0)) %>%
  group_by(response) %>% mutate(x = sum(pred)) %>% ungroup() %>%
  arrange(desc(x)) %>% mutate(response = fct_inorder(response))

fig_yeast_mass_p <- yeast_mass_p %>%
  mutate(num_predictors = as.factor(num_predictors)) %>%
  ggplot(., aes(x = num_predictors, y = response)) +
  geom_tile(aes(fill = as.factor(pred)), colour = "gray") +
  labs(x = "Number of Predictors") +
  scale_x_discrete(breaks = as.character(unique(c(1, seq(5, max(yeast_mass_p$num_predictors), 5), max(yeast_mass_p$num_predictors))))) +
  scale_y_discrete(position = "right") +
  scale_fill_manual(values = c("0" = "black", "1" = "gray"), guide = NULL) +
  theme_minimal() +
  theme(text = element_text(size = 14, color = "black"),
        axis.title.y = element_blank(), 
        axis.text.y.right = element_text(hjust = .5)
        )
fig_yeast_mass_p
```


```{r}
# function for Shannon entropy
entropy <- function(target) {
  freq <- table(target)/length(target)
  # vectorize
  vec <- as.data.frame(freq)[,2]
  #drop 0 to avoid NaN resulting from log2
  vec<-vec[vec>0]
  #compute entropy
  -sum(vec * log2(vec))
}

# compute entropy
e <- lapply(select(yeastdat, -species), entropy) 
# format data
# match order to heatmap of c sources selected as predictors
ent <- tibble(carbon_source = names(e),
                  entropy = unlist(e)) %>%
  filter(carbon_source != "D-Glucose") %>%
  mutate(carbon_source = factor(carbon_source, levels(yeast_mass_p$response)))
```

```{r}
### Figure bar graphs: Entropy ###
fig_yeast_mass_ent <- ent %>%
  ggplot(aes(x = carbon_source, y = as.numeric(entropy), fill = carbon_source)) +
  geom_col(width = 1) +
  scale_fill_viridis_d(direction = -1) +
  scale_y_continuous(breaks = c(0,.5,1)) +
  guides(fill = "none") +
  labs(x = "",
       y = "Shannon Entropy") +
  coord_flip() +
  theme_classic() +
  theme(text = element_text(size = 14, color = "black"),
        # axis.text.y = element_text(hjust = 0.5, colour = "black"),
        axis.text.y = element_blank()
        )
fig_yeast_mass_ent
```

## RF performance
```{r}
# read balanced accuracy scores (calculated over all RFs per predictor)
read_performance_scores <- function(fname){
  ret <- read_csv(fname) %>%
    dplyr::rename(num_predictors = `# of predictors`)
  col <- colnames(ret)
  col <- col[[length(col)]]
  ret <- ret %>%
    group_by(num_predictors, i, predictors) %>%
    summarise("mean_{col}" := mean( .data[[col]]  )) %>%
    ungroup() %>%
    mutate(mass_prediction = case_when(
      i == 0 ~ "MASS",
      i == 1 ~ "entropy",
      TRUE ~ "random"
    )) %>%
    mutate(num_predictors = factor(num_predictors, levels = 1:36)) %>%
    arrange(num_predictors)
  return(ret)
}

yeast_baseline_stats <- read_performance_scores("../Feature_subsetting/result/MIP_yeast_baseline_20230411_stats-acc.csv") %>%
  left_join(., read_performance_scores("../Feature_subsetting/result/MIP_yeast_baseline_20230411_stats-bacc.csv"), by = c("num_predictors", "i", "predictors", "mass_prediction")) %>%
  left_join(., read_performance_scores("../Feature_subsetting/result/MIP_yeast_baseline_20230411_stats-f1weighted.csv"), by = c("num_predictors", "i", "predictors", "mass_prediction")) %>%
  left_join(., read_performance_scores("../Feature_subsetting/result/MIP_yeast_baseline_20230411_stats-jaccard.csv"), by = c("num_predictors", "i", "predictors", "mass_prediction")) %>%
  left_join(., read_performance_scores("../Feature_subsetting/result/MIP_yeast_baseline_20230411_stats-cohen_kappa.csv"), by = c("num_predictors", "i", "predictors", "mass_prediction")) %>%
  left_join(., read_performance_scores("../Feature_subsetting/result/MIP_yeast_baseline_20230411_stats-mcc.csv"), by = c("num_predictors", "i", "predictors", "mass_prediction"))

# just MCC
fig_yeast_mass_mcc <- yeast_baseline_stats %>%
  ggplot(., aes(num_predictors, mean_mcc, color = mass_prediction)) +
  geom_point(aes(shape = mass_prediction, size = mass_prediction), position = position_jitter(width = .2, height = 0), alpha = .6) +
  stat_summary(aes(group = mass_prediction), geom = 'line', fun = 'mean', linewidth = 1) +
  scale_color_brewer(palette = "Set1", name = "RF with", labels = c("random" = "random predictors (n=300)", "MASS" = "MASS-selected predictors", "entropy" = "max-entropy-selected predictors")) +
  scale_shape_manual(values = c("random" = 1, "MASS" = 16, "entropy" = 16), guide = 'none') +
  scale_size_manual(values = c("random" = .4, "MASS" = 2, "entropy" = 2), guide = 'none') +
  # scale_alpha_manual(values = c("random" = 1, "MASS" = 16, "entropy" = 16), guide = 'none') +
  scale_x_discrete(drop = FALSE, breaks = my_breaks) +
  labs(#title = "Yeast dataset: RF performance ~ #predictors",
       x = "# predictors",
       y = "mean(MCC over all RF predictions)") +
  theme_classic() +
  theme(legend.position = "bottom")
fig_yeast_mass_mcc
```

## Plot assembly

```{r}
# plot assembly
png(filename = "fig-yeast-mass.png", width = 5500, height = 4300, res = 300)
wrap_plots(A = fig_yeast_hm_cond,
           B = guide_area(), 
           C = fig_yeast_hm,
           D = fig_yeast_hm_org,
           E = fig_yeast_mass_p,
           F = fig_yeast_mass_ent,
           G = (fig_yeast_mass_mcc + theme(axis.title.x = element_text(vjust = 25)) + plot_layout(guides = 'keep')),
           design = '
AAAABEEEEF
CCCCDEEEEF
CCCCDEEEEF
CCCCDEEEEF
CCCCDEEEEF
CCCCDGGGGG
CCCCDGGGGG
CCCCDGGGGG
CCCCDGGGGG
CCCCDGGGGG
', guides = 'collect') +
  plot_annotation(tag_levels = list(c("A", "", "", "B", "C", "D", "E"))) & 
  theme(plot.tag = element_text(size = 18))
dev.off()
```

## TODO include 2nd marginal prevalence plot???
```{r}
# percentage of bacdive species fermenting on each carbon source
fig_yeast_hm_cond_byp <- yeast_hm %>%
  filter(condition != "D-Glucose") %>%
  mutate(condition = factor(condition, levels = levels(yeast_mass_p$response))) %>%
  ggplot(aes(x = condition, fill = as.factor(phenotype))) +
  geom_bar(position = "fill", width = 1) +
  scale_y_continuous(labels = scales::percent, breaks = c(0,.5,1)) +
  theme_classic() +
  theme(text = element_text(size = 14, color = "black"),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank()
        ) +
    #theme(text = element_blank()) +
  scale_fill_viridis_d(guide = NULL) +
  coord_flip() +
  guides(fill = "none") +
  labs(x = "Carbon Source",
       y = "Percentage of Species")
fig_yeast_hm_cond_byp
# variance of each condition
fig_yeast_hm_cond_var <- yeast_hm %>%
  filter(condition != "D-Glucose") %>%
  group_by(condition) %>%
  summarise(var = var(phenotype)) %>%
  ungroup() %>%
  mutate(condition = factor(condition, levels = levels(yeast_mass_p$response))) %>%
  ggplot(aes(x = condition, y = as.numeric(var))) +
  geom_col(width = 1) +
  geom_hline(yintercept = .35) +
  scale_y_continuous(breaks = c(0,.5,1)) +
  guides(fill = "none") +
  labs(x = "",
       y = "Variance") +
  coord_flip() +
  theme_classic() +
  theme(text = element_text(size = 14, color = "black"),
        # axis.text.y = element_text(hjust = 0.5, colour = "black"),
        axis.text.y = element_blank()
        )
fig_yeast_hm_cond_var
# plot assembly
#png(filename = "fig-yeast-mass-woAcc.png", width = 6500, height = 3500, res = 300)
wrap_plots(A = fig_yeast_hm_cond,
           B = guide_area(), 
           C = fig_yeast_hm,
           D = fig_yeast_hm_org,
           E = fig_yeast_mass_p,
           F = fig_yeast_mass_ent,
           G = fig_yeast_hm_cond_byp,
           design = '
AAAABEEEEFG
CCCCDEEEEFG
CCCCDEEEEFG
CCCCDEEEEFG
CCCCDEEEEFG
CCCCDEEEEFG
CCCCDEEEEFG
CCCCDEEEEFG
', guides = 'collect') +
  plot_annotation(tag_levels = list(c("A", "", "", "B", "C", "D"))) & 
  theme(plot.tag = element_text(size = 18))
#dev.off()
```






# TODO: Supplementary Figure: ???? 
```{r}
### Figure S1 ###
rwdat <- readxl::read_xlsx(here("yeast_data", "summary_2ndEdition.xlsx"), sheet = "Sheet1", trim_ws = TRUE) %>% 
  filter(!strain == "dummyVars") %>%
  select(c(cSources$carbon_source, "strain")) %>%
  setNames(tolower(gsub("growth", "", names(.))))
rwdat <- readxl::read_xlsx("summary_2ndEdition.xlsx", sheet = "Sheet1", trim_ws = TRUE) %>% 
  filter(!strain == "dummyVars") %>%
  select(c(cSources$carbon_source, "strain")) %>%
  setNames(tolower(gsub("growth", "", names(.))))

allyeast <- rwdat %>%
  mutate(across(everything(), ~replace(., . == "+", "P"))) %>%
  mutate(across(everything(), ~replace(., . == "-", "N"))) %>%
  mutate(across(everything(), ~replace(., . == "?", NA))) %>%
  drop_na() %>%
  select(strain, everything())

yeastLong <- allyeast %>%
  pivot_longer(-strain, names_to = "carbon_source", values_to = "phenotype") %>%
  mutate(phenotype = factor(phenotype, levels = c("P", "N", "D", "V", "W")))

yeastLong %>%
  ggplot(aes(x = phenotype, group = carbon_source, fill = phenotype)) +
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") +
  scale_y_continuous(labels=scales::percent) +
  facet_wrap(~carbon_source, ncol = 5) +
  theme_classic() +
  theme(text = element_text(size =  14, color = "black"),
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.position = c(0.8, 0.05), legend.direction = "horizontal") +
  scale_fill_viridis(option = "G", discrete = TRUE, labels = c("Positive", "Negative", "Delayed", "Variable", "Weak")) +
  labs(x = "Growth",
       y = "Percentage of Strains",
       fill = "Phenotype") +
  guides(fill=guide_legend(title.position = "top", nrow=2,byrow=TRUE))

```

```{r}
### Figure S2B ###
y <- yeastf1_wide %>%
  select(-num_predictors) %>% 
  colSums()
yeast_pred <- data_frame(carbon_source = tolower(names(y)),
                         num_pred = y)
ent2 <- ent %>%
  mutate(entropy = as.numeric(entropy)) %>%
  inner_join(yeast_pred, by = "carbon_source")

ent2 %>%
  ggplot(aes(x = entropy, y = num_pred)) +
  geom_point() +
  theme_classic() +
  theme(text = element_text(size = 14)) +
  scale_y_continuous(breaks = scales::pretty_breaks(10)) +
  
  labs(x = "Shannon Entropy",
       y = "Times Selected as Predictor")
```

## Supplementary figure: all RF performance scores
```{r}
png(filename = "fig-supp-yeast-rf_perf_all.png", width = 3500, height = 2000, res = 300)
fig_yeast_rf_perf_all <- yeast_baseline_stats %>%
  pivot_longer(starts_with("mean_"), names_to = "performance_score", values_to = "performance_value") %>%
  ggplot(., aes(num_predictors, performance_value, color = mass_prediction)) +
  geom_point(aes(shape = mass_prediction, size = mass_prediction), position = position_jitter(width = .2, height = 0), alpha = .6) +
  stat_summary(aes(group = mass_prediction), geom = 'line', fun = 'mean', linewidth = 1) +
  scale_color_brewer(palette = "Set1", name = "RF with", labels = c("random" = "random predictors (n=300)", "MASS" = "MASS-selected predictors", "entropy" = "max-entropy-selected predictors")) +
  scale_shape_manual(values = c("random" = 1, "MASS" = 16, "entropy" = 16), guide = 'none') +
  scale_size_manual(values = c("random" = .4, "MASS" = 2, "entropy" = 2), guide = 'none') +
  # scale_alpha_manual(values = c("random" = 1, "MASS" = 16, "entropy" = 16), guide = 'none') +
  scale_x_discrete(drop = FALSE, breaks = my_breaks) +
  labs(title = "Yeast dataset: RF performance ~ #predictors",
       x = "# predictors",
       # y = "mean(balanced accuracy over all RF predictions)",
       y = "mean(respect. performance score over all RF predictions)") +
    facet_wrap(facets = vars(performance_score), ncol = 2) +
  theme_classic() +
  theme(legend.position = "bottom")
fig_yeast_rf_perf_all
dev.off()
```


# Session Info
```{r}
sessionInfo()
```